trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureServiceConnection: '<your-service-connection-name>'
  resourceGroupName: 'my-sample-resource-group'
  location: 'switzerlandnorth'
  templateFile: 'resource-group-template.json'

stages:
- stage: DeployResourceGroup
  displayName: 'Deploy Resource Group'
  jobs:
  - deployment: DeployToProduction
    displayName: 'Deploy to Production'
    environment: 'Production'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo "Starting deployment to $(resourceGroupName) in $(location)"
          - task: AzureResourceManagerTemplateDeployment@3
            inputs:
              deploymentScope: 'Subscription'
              azureResourceManagerConnection: $(azureServiceConnection)
              subscriptionId: '<your-subscription-id>'
              location: $(location)
              csmFile: $(templateFile)
              overrideParameters: |
                -resourceGroupName $(resourceGroupName)
                -location $(location)
              deploymentMode: 'Incremental'
          - script: echo "##vso[task.logissue type=warning]Deployment completed for $(resourceGroupName) in $(location)"
